name: 'Check revdate'
description: 'Checks for files in the /pages subdirectory that have been modified, but do not have their corresponding :revdate attribute updated.'
inputs:
  token:
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check if revdate is missing
      id: check-revdate
      continue-on-error: true
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        result=$(helpers/scripts/recurring/check_revdate ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
        if [[ -n "$result" ]]; then
          mkdir comment-artifact
          echo "As of ${{ github.event.pull_request.head.sha }}, the following files have been modified without a corresponding update to the \`revdate\` page attribute. If this is intentional, please ignore this message. 
          
          For guidance on when to update the \`revdate\` page attribute, please refer to the [SUSE Style Guide](https://documentation.suse.com/style/current/single-html/style-guide-adoc/index.html#sec-revinfo).
          
          \`\`\`
          $result
          \`\`\`
          " >> comment-artifact/body-revdate.txt
          echo ${{ github.event.pull_request.number }} >> comment-artifact/pr-num.txt
          exit 0
        else
          exit 1
        fi
      shell: bash

    - name: Upload comment-artifact
      if: steps.check-revdate.conclusion == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: comment-artifact
        path: comment-artifact
      