include::partial$variables.adoc[]

= Solução de problemas
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-09-04
:page-revdate: {revdate}
:description: Etapas de solução de problemas para {project-name}.

== Solução rápida de problemas

O Assistente de IA vive no cluster local no `cattle-ai-agent-system`namespace. Os logs do agente podem ser acessados para entender quaisquer problemas.

[source,bash]
----
kubectl get po -n cattle-ai-agent-system
----

Para obter logs do pod ‘rancher-ai-agent’:
[source,bash]
----
kubectl logs -n cattle-ai-agent-system -l app=rancher-ai-agent
----

Para obter logs do pod ‘rancher-ai-mcp’:
[source,bash]
----
kubectl logs -n cattle-ai-agent-system -l app=rancher-mcp-server
----

== Ativar log de depuração

Você pode ativar o log de depuração, usando `log.level=debug` durante a implantação do helm do Agente.

[NOTE]
====
Se você configurou o modelo pela página de configurações, por favor, reporte as configurações de volta no arquivo de valores antes de atualizar.
====

Atualizar o values.yaml
[source,yaml]
----
...
log:
  level: debug
...
----

Atualizar o chart:
[source,bash,subs="attributes+"]
----
helm upgrade -n cattle-ai-agent-system -f values.yaml rancher-ai-agent {oci-reg}
----

== Rancher por trás de certificado inseguro

Se o seu gerenciador Rancher estiver usando um certificado autoassinado, por favor, use `insecureSkipTls=true` para permitir que o servidor MCP se conecte ao Rancher.

[NOTE]
====
Se você configurou o modelo pela página de configurações, por favor, reporte as configurações de volta no arquivo de valores antes de atualizar.
====

[WARNING]
====
Se o chart já foi implantado. Você precisa excluir a implantação do rancher-mcp-server antes de atualizar o chart.
[source,bash,subs="attributes+"]
----
kubectl delete deployments.apps -n cattle-ai-agent-system rancher-mcp-server
----
====

Atualizar o values.yaml
[source,yaml]
----
...
insecureSkipTls: true
...
----

Atualizar o chart:
[source,bash,subs="attributes+"]
----
helm upgrade -n cattle-ai-agent-system -f values.yaml rancher-ai-agent {oci-reg}
----