name: Tasks needing write permissions

on:
  workflow_call:

jobs:
  add-comment:
    if: github.event.workflow_run.name == 'Test deployment'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: read
    steps:
      - name: Download artifact
        id: download-artifact
        continue-on-error: true
        uses: actions/download-artifact@v5
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}
          name: comment-artifact
          path: comment-artifact
      - name: Add a PR comment
        if: steps.download-artifact.outcome == 'success'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          touch comment-body.txt
          PR_NUMBER=$(cat comment-artifact/pr-num.txt)

          for comment in comment-artifact/body-*.txt; do
            cat $comment >> comment-body.txt
            echo "" >> comment-body.txt 
          done

          gh pr comment $PR_NUMBER \
           --edit-last \
           --create-if-none \
           --body-file comment-body.txt \
           --repo ${{ github.event.workflow_run.repository.full_name }}
      
