include::partial$variables.adoc[]

= Troubleshooting
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-09-04
:page-revdate: {revdate}
:description: Troubleshooting steps for {project-name}.

== Quick troubleshooting

The AI Assistant lives in the Local cluster in the `cattle-ai-agent-system`
namespace. Agent Logs can be accessed to understand any issues.

[source,bash]
----
kubectl get po -n cattle-ai-agent-system
----

To get logs from the ‘rancher-ai-agent’ pod:
[source,bash]
----
kubectl logs -n cattle-ai-agent-system -l app=rancher-ai-agent
----

To get logs from the ‘rancher-ai-mcp’ pod:
[source,bash]
----
kubectl logs -n cattle-ai-agent-system -l app=rancher-mcp-server
----

== Enable debug log

You can enable debugs log, using `log.level=debug` during the helm deployment
of the Agent.

[NOTE]
====
If you configured the model via the settings page, please report the settings back in the values file before updating.
====

Update the values.yaml
[source,yaml]
----
...
log:
  level: debug
...
----

Update the chart:
[source,bash,subs="attributes+"]
----
helm upgrade -n cattle-ai-agent-system -f values.yaml rancher-ai-agent {oci-reg}
----

== Rancher behind insecure certificate

If your Rancher manager is using a self-signed certificate, please use
`insecureSkipTls=true` to allow the MCP server to connect to Rancher.

[NOTE]
====
If you configured the model via the settings page, please report the settings back in the values file before updating.
====

[WARNING]
====
If the chart was already deployed. You need to delete the rancher-mcp-server deployment before upgrading the chart.
[source,bash,subs="attributes+"]
----
kubectl delete deployments.apps -n cattle-ai-agent-system rancher-mcp-server
----
====

Update the values.yaml
[source,yaml]
----
...
insecureSkipTls: true
...
----

Update the chart:
[source,bash,subs="attributes+"]
----
helm upgrade -n cattle-ai-agent-system -f values.yaml rancher-ai-agent {oci-reg}
----